/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanejarRouteImport } from './routes/planejar'
import { Route as RhRouteImport } from './routes/rh'
import { Route as RhIndexRouteImport } from './routes/rh.index'
import { Route as RhCreditosRouteImport } from './routes/rh.creditos'
import { Route as RhEsgRouteImport } from './routes/rh.esg'
import { Route as RhIntelligenceRouteImport } from './routes/rh.intelligence'
import { Route as RhMobilidadeRouteImport } from './routes/rh.mobilidade'
import { Route as RhPoliticasRouteImport } from './routes/rh.politicas'
import { Route as RhTransacoesRouteImport } from './routes/rh.transacoes'
import { Route as ApiMobilitySearchRouteImport } from './routes/api/mobility/search'
import { Route as RhColaboradoresIndexRouteImport } from './routes/rh.colaboradores.index'
import { Route as RhColaboradoresIdRouteImport } from './routes/rh.colaboradores.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejarRoute = PlanejarRouteImport.update({
  id: '/planejar',
  path: '/planejar',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const RhIndexRoute = RhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RhRoute,
} as any)
const RhCreditosRoute = RhCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => RhRoute,
} as any)
const RhEsgRoute = RhEsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => RhRoute,
} as any)
const RhIntelligenceRoute = RhIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => RhRoute,
} as any)
const RhMobilidadeRoute = RhMobilidadeRouteImport.update({
  id: '/mobilidade',
  path: '/mobilidade',
  getParentRoute: () => RhRoute,
} as any)
const RhPoliticasRoute = RhPoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => RhRoute,
} as any)
const RhTransacoesRoute = RhTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => RhRoute,
} as any)
const ApiMobilitySearchRoute = ApiMobilitySearchRouteImport.update({
  id: '/api/mobility/search',
  path: '/api/mobility/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RhColaboradoresIndexRoute = RhColaboradoresIndexRouteImport.update({
  id: '/colaboradores/',
  path: '/colaboradores/',
  getParentRoute: () => RhRoute,
} as any)
const RhColaboradoresIdRoute = RhColaboradoresIdRouteImport.update({
  id: '/colaboradores/$id',
  path: '/colaboradores/$id',
  getParentRoute: () => RhRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planejar': typeof PlanejarRoute
  '/rh': typeof RhRouteWithChildren
  '/rh/creditos': typeof RhCreditosRoute
  '/rh/esg': typeof RhEsgRoute
  '/rh/intelligence': typeof RhIntelligenceRoute
  '/rh/mobilidade': typeof RhMobilidadeRoute
  '/rh/politicas': typeof RhPoliticasRoute
  '/rh/transacoes': typeof RhTransacoesRoute
  '/rh/': typeof RhIndexRoute
  '/api/mobility/search': typeof ApiMobilitySearchRoute
  '/rh/colaboradores/$id': typeof RhColaboradoresIdRoute
  '/rh/colaboradores/': typeof RhColaboradoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planejar': typeof PlanejarRoute
  '/rh/creditos': typeof RhCreditosRoute
  '/rh/esg': typeof RhEsgRoute
  '/rh/intelligence': typeof RhIntelligenceRoute
  '/rh/mobilidade': typeof RhMobilidadeRoute
  '/rh/politicas': typeof RhPoliticasRoute
  '/rh/transacoes': typeof RhTransacoesRoute
  '/rh': typeof RhIndexRoute
  '/api/mobility/search': typeof ApiMobilitySearchRoute
  '/rh/colaboradores/$id': typeof RhColaboradoresIdRoute
  '/rh/colaboradores': typeof RhColaboradoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planejar': typeof PlanejarRoute
  '/rh': typeof RhRouteWithChildren
  '/rh/creditos': typeof RhCreditosRoute
  '/rh/esg': typeof RhEsgRoute
  '/rh/intelligence': typeof RhIntelligenceRoute
  '/rh/mobilidade': typeof RhMobilidadeRoute
  '/rh/politicas': typeof RhPoliticasRoute
  '/rh/transacoes': typeof RhTransacoesRoute
  '/rh/': typeof RhIndexRoute
  '/api/mobility/search': typeof ApiMobilitySearchRoute
  '/rh/colaboradores/$id': typeof RhColaboradoresIdRoute
  '/rh/colaboradores/': typeof RhColaboradoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/planejar'
    | '/rh'
    | '/rh/creditos'
    | '/rh/esg'
    | '/rh/intelligence'
    | '/rh/mobilidade'
    | '/rh/politicas'
    | '/rh/transacoes'
    | '/rh/'
    | '/api/mobility/search'
    | '/rh/colaboradores/$id'
    | '/rh/colaboradores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/planejar'
    | '/rh/creditos'
    | '/rh/esg'
    | '/rh/intelligence'
    | '/rh/mobilidade'
    | '/rh/politicas'
    | '/rh/transacoes'
    | '/rh'
    | '/api/mobility/search'
    | '/rh/colaboradores/$id'
    | '/rh/colaboradores'
  id:
    | '__root__'
    | '/'
    | '/planejar'
    | '/rh'
    | '/rh/creditos'
    | '/rh/esg'
    | '/rh/intelligence'
    | '/rh/mobilidade'
    | '/rh/politicas'
    | '/rh/transacoes'
    | '/rh/'
    | '/api/mobility/search'
    | '/rh/colaboradores/$id'
    | '/rh/colaboradores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanejarRoute: typeof PlanejarRoute
  RhRoute: typeof RhRouteWithChildren
  ApiMobilitySearchRoute: typeof ApiMobilitySearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejar': {
      id: '/planejar'
      path: '/planejar'
      fullPath: '/planejar'
      preLoaderRoute: typeof PlanejarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/': {
      id: '/rh/'
      path: '/'
      fullPath: '/rh/'
      preLoaderRoute: typeof RhIndexRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/creditos': {
      id: '/rh/creditos'
      path: '/creditos'
      fullPath: '/rh/creditos'
      preLoaderRoute: typeof RhCreditosRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/esg': {
      id: '/rh/esg'
      path: '/esg'
      fullPath: '/rh/esg'
      preLoaderRoute: typeof RhEsgRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/intelligence': {
      id: '/rh/intelligence'
      path: '/intelligence'
      fullPath: '/rh/intelligence'
      preLoaderRoute: typeof RhIntelligenceRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/mobilidade': {
      id: '/rh/mobilidade'
      path: '/mobilidade'
      fullPath: '/rh/mobilidade'
      preLoaderRoute: typeof RhMobilidadeRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/politicas': {
      id: '/rh/politicas'
      path: '/politicas'
      fullPath: '/rh/politicas'
      preLoaderRoute: typeof RhPoliticasRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/transacoes': {
      id: '/rh/transacoes'
      path: '/transacoes'
      fullPath: '/rh/transacoes'
      preLoaderRoute: typeof RhTransacoesRouteImport
      parentRoute: typeof RhRoute
    }
    '/api/mobility/search': {
      id: '/api/mobility/search'
      path: '/api/mobility/search'
      fullPath: '/api/mobility/search'
      preLoaderRoute: typeof ApiMobilitySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/colaboradores/': {
      id: '/rh/colaboradores/'
      path: '/colaboradores'
      fullPath: '/rh/colaboradores/'
      preLoaderRoute: typeof RhColaboradoresIndexRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/colaboradores/$id': {
      id: '/rh/colaboradores/$id'
      path: '/colaboradores/$id'
      fullPath: '/rh/colaboradores/$id'
      preLoaderRoute: typeof RhColaboradoresIdRouteImport
      parentRoute: typeof RhRoute
    }
  }
}

interface RhRouteChildren {
  RhCreditosRoute: typeof RhCreditosRoute
  RhEsgRoute: typeof RhEsgRoute
  RhIntelligenceRoute: typeof RhIntelligenceRoute
  RhMobilidadeRoute: typeof RhMobilidadeRoute
  RhPoliticasRoute: typeof RhPoliticasRoute
  RhTransacoesRoute: typeof RhTransacoesRoute
  RhIndexRoute: typeof RhIndexRoute
  RhColaboradoresIdRoute: typeof RhColaboradoresIdRoute
  RhColaboradoresIndexRoute: typeof RhColaboradoresIndexRoute
}

const RhRouteChildren: RhRouteChildren = {
  RhCreditosRoute: RhCreditosRoute,
  RhEsgRoute: RhEsgRoute,
  RhIntelligenceRoute: RhIntelligenceRoute,
  RhMobilidadeRoute: RhMobilidadeRoute,
  RhPoliticasRoute: RhPoliticasRoute,
  RhTransacoesRoute: RhTransacoesRoute,
  RhIndexRoute: RhIndexRoute,
  RhColaboradoresIdRoute: RhColaboradoresIdRoute,
  RhColaboradoresIndexRoute: RhColaboradoresIndexRoute,
}

const RhRouteWithChildren = RhRoute._addFileChildren(RhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanejarRoute: PlanejarRoute,
  RhRoute: RhRouteWithChildren,
  ApiMobilitySearchRoute: ApiMobilitySearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
